---
name: Build and Publish hashicorp/serf container-image

on:
  push:
    branches: ["master"]
    paths: ["serf/Containerfile"]
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build:
    name: Build and push container-image to ghcr.io
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      # - uses: docker/setup-buildx-action@v1
      - name: Login to GHCR
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Publish
        uses: docker/build-push-action@v2
        with:
          context: serf
          file: serf/Containerfile
          push: true
          tags: ghcr.io/jmanero/serf:latest
